### ISSUE TITLE
Helm upgrade doesn't always work properly

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#123]
When running `helm upgrade`, some objects (e.g. the configmap) aren't recreated even though when rendering them they are different than the previously submitted version. To be more specific:

```
helm install --name gateway --values config.yaml dask-gateway/dask-gateway
helm upgrade gateway dask-gateway/dask-gateway --values new-config.yaml
```

where `new-config.yaml` changes something like `gateway.clusterManager.environment` (which in turn results in a new `configmap`), none of the objects are recreated. If I delete the configmap and then run `helm upgrade`, the new configmap is written and things upgrade properly.

This may be a case of https://github.com/helm/helm/issues/5915, but there's likely something we can do about it.

**Comment by jcrist** [comment]
One idea I saw somewhere was to include a hash or timestamp in the label to better trigger a redeployment.

**Comment by yuvipanda** [comment]
Yup, generally stuff gets updated rather than recreated. If you mount a configmap as a volume, the contents will dynamically change when your configmap changes. If you want your deployments / statefulsets to roll over, adding an annotation with the hash is the right way to go - see https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

**Comment by yuvipanda** [comment]
As an aside, I recommendusing the --install flag to helm upgrade, rather than a separate helm install command. Helps me keep things simpler

**Comment by jcrist** [comment]
Thanks @yuvipanda, this was done in #143.
