### ISSUE TITLE
Reuse of existing codebases

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-gateway#153]
I would like to raise a small concern I have around the ongoing maintenance of this project.

I would really like to see if we can make use of the existing kubernetes, jobqueue and yarn cluster managers in dask-gateway. I'm aware that due to some differences in requirements, all of those cluster managers have been reimplemented in dask-gateway. But this does add quite a bit of maintenance overhead supporting multiple similar code bases within the Dask project. I can imagine a need to port bug fixes and enhancements between multiple libraries.

My initial suggestion for this would be to make those packages a dependency of this one and slowly begin pushing things upstream. 

One example of this from the kubernetes side would be the spec creation functions. There is already a lot of logic in dask-kubernetes to handle this, expecially around cleaning and validation, but reading through the implementation here there are some improvements over the way it's done in that package. It could be good to mix the implementations in the dask-kubernetes package and depend on that single implementation in both places.

I would be really keen to hear other's thoughts on this.

@jcrist @mrocklin @jhamman @yuvipanda @lesteve @guillaumeeb

**Comment by jcrist** [comment]
Thanks for bringing this up. I've had this conversation a few times now, it'd be good to have a shared conversation here. 

Dask-Gateway has different design constraints than the other dask cluster managers which made reimplementing make more sense at the time. This may change in the future, but I'd like to dive into why things are the way the are.

Dask-Gateway has the following requirements:
- All state must be serializable to a database to allow for persistence and failover. We avoid objects here, and make use of state dictionaries for tracking individual worker/scheduler state.
- When applicable, all clusters must be started as the requesting user by the cluster backend, which means dask-gateway needs to tie into the auth system of the cluster backend and be able to use whatever admin permissions are necessary to do so. For YARN this means submitting/querying/stopping applications as a proxy user. For HPC this means using sudo, and maybe some queue-specific permissions (e.g. PBS operator).
- Since we're tracking many applications for many users, we need to be efficient. For example, when tracking job status for HPC systems, all job queries are pooled together so there's only one periodic call to e.g. qsub. For kubernetes we use the reflector pattern.
- All operations need to be robust to failure. If an operation fails, we need to roll it back. If the gateway fails, we need to be able to recover from the database.

All of these requirements have led to a [different base class](https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/managers/base.py) for a cluster manager than is used by other dask clusters. Different requirements lead to different interfaces - accomplishing the above with the existing `distributed.deploy.cluster.Cluster` classes would have been hard if not impossible.

---

Since the way we start, stop, and check the status of a process will usually need to differ between dask-gateway and other cluster managers, the only remaining bit of code that could be shared would be the code generating the process specs. Most cluster backends have some kind of specification for what a process looks like:
- Kubernetes has the Pod Spec
- YARN uses [Skein's](https://github.com/jcrist/skein) Specification
- HPC systems have job scripts

Perhaps code could be shared between these projects for generating these specs? Since you're most familiar with `dask-kubernetes`, lets compare what objects we need to generate to see if its worth sharing:

In dask-gateway we create the following kubernetes objects for each cluster
- A secret holding TLS credentials
- A scheduler pod
- Many worker pods

The code for all of this lives here: 
- [Secret spec](https://github.com/dask/dask-gateway/blob/d1332521b86ad78813df8150806826e5eb0ae754/dask-gateway-server/dask_gateway_server/managers/kubernetes.py#L539-L553)
- [Pod spec](https://github.com/dask/dask-gateway/blob/d1332521b86ad78813df8150806826e5eb0ae754/dask-gateway-server/dask_gateway_server/managers/kubernetes.py#L555-L626)

and is remarkably short. Mostly declarative, < 100 lines including comments and black's vertical-space-heavy formatting. And it's specific to the needs of this project - dask-kubernetes requires a different spec (including a service object), merging these codebases would make the spec generating code more complicated to support both use cases. The same is true for the other cluster managers - generating the process spec is usually pretty small and easily digested (the [YARN one](https://github.com/dask/dask-gateway/blob/d1332521b86ad78813df8150806826e5eb0ae754/dask-gateway-server/dask_gateway_server/managers/yarn.py#L241-L285) is ~40 lines, the [PBS one](https://github.com/dask/dask-gateway/blob/d1332521b86ad78813df8150806826e5eb0ae754/dask-gateway-server/dask_gateway_server/managers/jobqueue/pbs.py#L132-L165) is ~32).

While these implementations likely could be shared between projects, I'm going to argue that they're easily maintained in their current location, and moving them to the non-gateway respective subprojects would increase coupling and make things harder to change in the future.  This project is still evolving - if the interface requirements change here we'd have to make changes upstream and synchronize releases. Moving the code out into a separate project also would increase [indirection](http://matthewrocklin.com/blog/work/2019/06/23/avoid-indirection) making the code here harder to understand and maintain.

---

To be clear, I'm not 100% against sharing code between these projects. But as things stand the different backend requirements mean that little of the code can be shared, and what can be shared is easy small enough that I don't think the maintenance burden of having multiple code bases to coordinate is worth the benefit.

**Comment by jacobtomlinson** [comment]
Thanks for the thorough response, it really helps to understand your thinking.

I can see why the requirements here mean that you are not able to use the existing cluster managers. However I feel like those requirements are orthogonal to those of the cluster managers. I don't see any reason why they couldn't be modified in ways which fit those requirements.

An even simpler example would be when developing new cluster managers for `dask-cloudprovider` would it be beneficial to think about how it could be done to satisfy both use cases?

The [pod spec function](https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/objects.py#L100-L163) from dask-kubernetes is very similar to the one here. I agree that indirection should be kept to a minimum but in this case we have two very similar functions, both of which will need maintaining over time. I also appreciate that many of these functionary are only tens of lines, but there are many of them and they will only grow with time. 

There are also features here that it would be nice to see in other places. The way you are tracking the pod state here is great and would be nice to have in `dask-kubernetes`. By breaking the dependency chain and rewriting code it makes it harder to get stuff pushed back and shared.

I also understand your concern about coupling and handling multiple packages and releases. But I would push the point that this is why strong APIs, short release cycles and semantic versioning are really important, along with automated tests and deployments. Together they ease this process.

**Comment by jcrist** [comment]
I don't disagree that things could be shared with work, but I have limited time to do this work and don't see it as terribly important in the near term. FWIW, maintaining the cluster managers in dask-gateway is not a large maintenance burden. I suspect that moving things out to depend on dask-kubernetes would increase this maintenance burden with little perceivable benefit for the project. I guess my thought here is "things work already, why change them?".

> I also understand your concern about coupling and handling multiple packages and releases. But I would push the point that this is why strong APIs, short release cycles and semantic versioning are really important, along with automated tests and deployments.

Since this project is young and things may change, we don't have strong APIs. And moving things out to a separate repo will complicate changes in the future. Say I want to add a new feature to the kubernetes cluster manager that's dask-gateway specific. Right now I can push a fix to this repo along with its tests, make sure everything works, merge it, and issue a release of dask-gateway. If things were separated I'd have to patch both dask-kubernetes and dask-gateway, test that things work fine on dask-gateway locally (since it's PRs to two projects), push to both projects, merge both, make sure dask-gateway's CI is testing with dask-kubernetes master branch and a release branch, release both projects, and ensure that dependency versions match. This is much more complicated, with as I see it little perceivable benefit.

**Comment by jcrist** [comment]
I guess my argument comes down to:

- These projects have different requirements, and will each need different features (even if some overlap). Thus some features will need to be able to be enabled/disabled, making the internals of a shared implementation more complicated.
- There is a maintenance burden to splitting code out into separate projects. There are also benefits, but the burden does exist (otherwise all software would just be composing tiny packages a la [left-pad](https://www.npmjs.com/package/left-pad)).
- For now I think the burden outweighs the cost. Moving things out would complicate both the individual implementations and general maintenance, bringing only the benefit of some code reuse (which I'd argue is small).

**Comment by mrocklin** [comment]
> I suspect that moving things out to depend on dask-kubernetes would increase this maintenance burden with little perceivable benefit for the project.

For Dask-Gateway, perhaps not, but for Dask generally I think that having you more actively defining conventions and policies would have a large positive impact.  

As an example, I really like the async-generator approach you have within dask-gateway to iterate over the stages of deployment.  We could probably use something like this upstream.  In particular, I think that it would help with adaptivity and workers.

> For now I think the burden outweighs the cost

This could definitely be the case.  I think that mostly I want to make sure that when counting up benefit we also consider the benefits upstream, and the network effect of consistency.  Certainly, if we're just thinking about dask-gateway then it probably makes sense to make a standalone project.  Probably even if we're optimizing for everything at once then it still makes sense to start dask-gateway as a standalone project until it has some success and has experimented with some of the ideas here. 

However, I think that we should think about upstreaming things well before it makes sense just from dask-gateway's perspective.  Mostly this is selfish from my perspective.  I want Jim's perspective to be more actively applied to dask-kubernetes and dask-jobqueue.

**Comment by jcrist** [comment]
> Probably even if we're optimizing for everything at once then it still makes sense to start dask-gateway as a standalone project until it has some success and has experimented with some of the ideas here.

👍

**Comment by jcrist** [comment]
Closing as not a specific, actionable issue. The backend structure of dask-gateway is sufficiently different from the `distributed.deploy.cluster.Cluster` base class that they can't be used directly. If in the future we want to move bits of the backends into their corresponding `dask-*` cluster-manager packages we can, but for now this doesn't seem to make sense.
