### ISSUE TITLE
Adding packages to dask-gateway on `new_cluster` call

### ISSUE THREAD

**Issue by qntnrbns** [dask/dask-gateway#159]
Hi all, I am wondering if there is a simple way to add new packages to clusters when you create them from the gateway.

**Comment by jcrist** [comment]
What's your use case? For what backend? Dask-gateway supports multiple backends (kubernetes, yarn, etc...) - each of these would require a different implementation for adding additional packages.

I think modifying a python environment at runtime is error prone - IMO users should build their environment once then deploy it on the cluster (using e.g. docker, conda-pack, etc...). We do support letting users modify the cluster specification at runtime using the [`cluster_options` kwarg](https://gateway.dask.org/api-client.html#dask_gateway.Gateway.new_cluster) (admittedly this is poorly documented). So if you're running on kubernetes you could enable users to specify their own docker image. On YARN you could let them specify the location of a bundled environment.

---

Alternatively, users can install stuff at runtime by shelling out to `pip`/`conda`. This is a bit hacky (and I don't advise it), but users do this all the time.

```
def update_environment():
    os.system("pip install -U my-special-package")

client.run(update_environment)
```

https://github.com/dask/distributed/pull/3216 would make this less hacky, but I still think modifying existing environments at runtime is ill-advised - at a minimum it slows down worker start times since the workers are installing at runtime, at worst it can result in broken environments and hard to diagnose errors.

---

If neither of these solutions work for you, you could add this feature you self by subclassing from a `ClusterManager` implementation and adding environment modification to the `start_cluster` call. I'm not sure how you'd want to implement this (it's backend specific), but it's possible.

**Comment by qntnrbns** [comment]
Thank you for the through response. 

I haven't been able to make the cluster options work. I am kind of confused about how the Option object functions. Could you point me to the relevant code section to help me figure it out?

**Comment by jcrist** [comment]
Sorry this isn't yet documented (I'll prioritize getting docs up).

User options need to be enabled on the server side in the config. The relevant traitlet config is `c.DaskGateway.cluster_manager_options`. This takes an instance of `dask_gateway_server.options.Options` which configures what options a user can set, and how the gateway server interprets them.

The `Options` object is documented (briefly) here: https://gateway.dask.org/api-server.html#dask_gateway_server.options.Options. It takes two things:

- One or more option fields that a user can set
- A handler for interpreting the values

Options don't have to map directly to traitlets on the `ClusterManager` - the handler can do anything you want with them. Further, you can validate the options - any error raised here will be returned to the user.

Here's the config we're currently using in the Pangeo project. This enables setting worker cores and memory, as well as the docker image to use (they're using the kubernetes cluster manager):

```python
    from dask_gateway_server.options import Options, Integer, Float, String
    def option_handler(options):
        if ":" not in options.image:
            raise ValueError("When specifying an image you must also provide a tag")
        return {
            "worker_cores_limit": options.worker_cores,
            "worker_memory": "%fG" % options.worker_memory,
            "image": options.image,
        }
    c.DaskGateway.cluster_manager_options = Options(
        Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
        Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
        String("image", default="daskgateway/dask-gateway:0.4.1", label="Image"),
        handler=option_handler,
    )
```

Note that when `cluster_manager_options` is configured, the options handler is *always* applied. If the user doesn't manually specify anything, the default values for each field will be used.

On the user side, users can specify options as kwargs to `Gateway.new_cluster`, or create a user-side options object by querying `Gateway.cluster_options()`. This returns a mapping-like object that also provides a nice IPyWidget. The users can configure the object programmatically or using the widget, then pass it to `new_cluster`.

![ipywidget](https://user-images.githubusercontent.com/2783717/60847253-b5031800-a1a7-11e9-9928-2c6244992a3f.png)

**Comment by jcrist** [comment]
I've added documentation on exposing cluster options to users. Can you take a look through https://gateway.dask.org/usage.html#configure-a-cluster and https://gateway.dask.org/cluster-options.html to see if they answer your questions.

**Comment by qntnrbns** [comment]
This is super helpful! Thank you!!! Where might we be able to find a list the options that `options_handler` can return?

**Comment by jcrist** [comment]
> Where might we be able to find a list the options that options_handler can return?

Does #172 answer your question?

**Comment by qntnrbns** [comment]
Yes it does thank you!

**Comment by jcrist** [comment]
Glad to hear it. Please file more issues like this if questions come up, they're really useful for improving the state of this project.

**Comment by kyprifog** [comment]
I dont quite follow from the documentation, is there a concise way for kubernetes to add extra pip packages to the workers (such as s3fs)

**Comment by droctothorpe** [comment]
You have two options:

(1) https://distributed.dask.org/en/latest/api.html#distributed.Client.run
(2) https://distributed.dask.org/en/latest/plugins.html#distributed.diagnostics.plugin.WorkerPlugin

(1) Works if you're scaling manually. Simply scale up to the desired worker count then execute a conda or pip install on all workers.
(2) Is necessary if you want to leverage auto-scaling.
