### ISSUE TITLE
Support dask-cuda workers

### ISSUE THREAD

**Issue by dankerrigan** [dask/dask-gateway#177]
dask-gateway appears to only support starting a cpu-based workers via `dask-gateway-worker`. In order to run [dask-cuda](https://github.com/rapidsai/dask-cuda), dask-gateway needs to be able to invoke `dask-cuda-worker` as well as pass GPU specific variables to `dask-cuda-worker`. Can dask-gateway be extended to support GPUs via RAPIDs? @mmccarty

**Comment by jcrist** [comment]
`dask-cuda-worker` is a small wrapper around the normal dask worker that sets up some common GPU related functionality. I'm reinterpreting this request as "support GPUs as resources in a way similar to `dask-cuda`". Is that fair?

Scheduling GPUs as resources on multiple machines is different than scheduling on a single machine (as done by `LocalCudaCluster`), we'll need to add GPU specific functionality to the various backends. All of this is doable, and may be done using `dask-cuda`, or with our own implementation (not sure which is better yet).

**Comment by dankerrigan** [comment]
Re your question, that sounds right.

**Comment by mmccarty** [comment]
@jcrist We are going test this out.

**Comment by felipeblazing** [comment]
@mmccarty @jcrist  Is this being looked at still? We really have a need for using something like dask gateway to set up distributed GPU clusters.

**Comment by mrocklin** [comment]
In general I've been thinking about giving deployment solutions like dask-gateway control over the dask-scheduler process (they'll probably need to add various hooks to specific services), but trying hard to allow users to specify their own vanilla dask-worker processes.  

Looking briefly at the current dask_cli file it looks like dask-gateway currently does have a custom dask-worker process.  I *think* that the only difference is that if a scheduler address isn't specified then it checks in with the gateway.  Is it possible to always provide a scheduler address?  If so, could dask-gateway's special handling of worker processes be removed so that this could go back into user control?

**Comment by mrocklin** [comment]
Hrm, it looks like the modifications to the scheduler are modest as well.  I wonder if we might be able to avoid more of the dask_gateway/dask_cli.py file by putting the scheduler functionality into a plugin and specifying that plugin in configuration.

**Comment by sami2ahmed** [comment]
@mmccarty @jcrist anything new on this? Thank you

**Comment by jcrist** [comment]
I have a WIP PR for handling this up in #300. Still need to fix the k8s backend.
