### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#228]
I think we're just about ready to release. This release includes a major rewrite of the server (for all backends). Below is a list of issues that need to be done before this release:

- [x] #223 
- [x] #224 
- [ ] Re-enable docs builds
- [x] Improve kubernetes documentation (at least a high-level pod diagram)

If there are other blocking issues, please comment below.

And the actual release process:
- [ ] Build packages, push to PyPI
- [ ] Update conda-forge feedstocks
- [ ] Build docker images, push to docker hub
- [ ] Build helm chart, push to repo
- [ ] Announce release

**Comment by consideRatio** [comment]
@jcrist thank you for all your work on this project! I saw [your PyData presentation](https://www.youtube.com/watch?time_continue=42&v=Q8Wy0RB5UKQ) that I found to be really good and perfect for me to watch! I'm aiming to deploy and become an active user of this helm chart before April's end.

I just installed the latest released 0.6.1 version of the chart and studied the existing values etc in master, but realize I want to work against master instead. Since there are no dev releases I'll download a local copy and update it for now.

In the future though... Would you like to have a PR for automating image build/tag/push to docker hub and chart package/push to your helm chart registry? It would be a PR to use chartpress in .travis.yml and include requests to stash some helm chart git repo and docker hub credentials in travis environment variables.

**Comment by jcrist** [comment]
Thanks @consideRatio. I'm between jobs right now, but will probably finish up this release sometime next week. I recommend either referencing the documentation for the latest release (0.6.1, our built docs are [here](https://gateway.dask.org/install-kube.html#helm-chart-reference)), or referencing master (which is unlikely to change much before release).

We would like to eventually automate building and pushing the chart/images - see #38 and #146 for more info. If we can do it without bringing in chartpress I'd prefer that (minimizes the number of tools needed).
