### ISSUE TITLE
Slow cluster startup time

### ISSUE THREAD

**Issue by rabernat** [dask/dask-gateway#262]
Using the latest dask-gateway 0.7.1 on pangeo GCP binder, I'm finding that it takes my cluster about 5 minutes to start.

```
from dask_gateway import Gateway
gateway = Gateway()
cluster = gateway.new_cluster() # this takes ~5 minutes
```

Is that expected? Is there some way we can reduce this startup time? Compared to kubecluster, it feels a quite slow.

**Comment by jcrist** [comment]
There's nothing intrinsic about dask-gateway that would make it slower to allocate clusters than dask-kubernetes (though in certain setups things may be slower). I suspect the issue here is:

- Dask-Gateway always runs the scheduler in it's own pod (opposed to dask-kubernetes where the scheduler is run locally, which starts pretty quick).
- The pangeo setup has dask-scheduler's running in a node pool that can scale down to 0.
- If the allocation of a scheduler pod requires a new node, this can take some time.

In my setup with nodes available, allocating a cluster happens in seconds (<10). The comparison with dask-kubernetes points out an interesting perception issue. Dask-Kubernetes likely runs into the same issues when allocating workers on a scalable node pool, but since you have a scheduler, waiting on workers to start is less visible to the user.

I made a few suggestions on ways to fix this here: https://github.com/pangeo-data/pangeo-cloud-federation/issues/587#issuecomment-617911743

**Comment by mrocklin** [comment]
That sounds like the time it takes to start up a new VM in a cold cluster.
Dask-gateway is running the scheduler in a separate pod rather than locally
(which is usually a good idea, but has this as a slight drawback).

**Comment by rabernat** [comment]
Thanks for the quick replies. I should add that there is quite a bit of variability to this, so it makes sense that it depends on the cluster state and node availability.
