### ISSUE TITLE
Implement HA with leader election for controller pod

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-gateway#391]
Please correct me if I'm wrong, but it looks like the controller pod doesn't support HA. Replica count is hard-coded to `1` in the [relevant Helm template](https://github.com/dask/dask-gateway/blob/main/resources/helm/dask-gateway/templates/controller/deployment.yaml#L9), and I'm not seeing any logic for handling multiple replicas in the controller.

For reference, Operator SDK and Kubebuilder handle this using leader election. [Here's](https://docs.openshift.com/container-platform/4.1/applications/operator_sdk/osdk-leader-election.html) a link to some relevant documentation. 

Would it make sense to implement leader election for the controller to support HA? If so, this would definitely be something that  my team would be interested in taking on. We're looking for upstream contribution opportunities.

**Comment by droctothorpe** [comment]
Should be pretty easy with [this](https://github.com/kubernetes-client/python-base/tree/master/leaderelection). I'd be happy to take a crack at it if y'all think it makes sense.

**Comment by consideRatio** [comment]
I'm triaging in the issues list and I think about this issue. I think this introduces a bit too much complexity to be merited the maintenance effort at this point with limited maintenance capacity.

The value of having ~0 downtime by HA on the controller is probably not critical either, the worst case is that someone has to wait a bit for a relocated controller starting up again.

> Should be pretty easy with [this](https://github.com/kubernetes-client/python-base/tree/master/leaderelection). I'd be happy to take a crack at it if y'all think it makes sense.

I'm not sure if its relevant as I've not digged into the details of that example, but I think we rely on `kubernetes_asyncio` (https://github.com/tomplus/kubernetes_asyncio) rather than `kubernetes` (https://github.com/kubernetes-client/python), but the difference is small so whatever works with the normal client will be made workable with the asyncio client as well I think.
