### ISSUE TITLE
Provide terraform projects for default backend setups

### ISSUE THREAD

**Issue by kpasko** [dask/dask-gateway#395]
Even if following e.g. zero-to-jupyterhub steps, it is easy to have a failing dask gateway (or dask/dask , dask/daskhub helm deployment for that matter). Worker set memory issues, incorrect networking/permissions settings, etc can all interfere, and there is limited documentation for debugging, gotchas, common issues etc.

While each deployment setup is of course different, an "MVP" deployment infrastructure for AWS/Azure/GC via terraform would greatly ease the barriers to entry of using dask gateway easily and successfully.

**Comment by jacobtomlinson** [comment]
I totally get where you are coming from.

It's tricky because Kubernetes clusters and infrastructure like this is so opinionated it's hard to open source things like this. I understand what you mean that an MVP deployment could be useful, but I feel like it would be a useful reference but probably not useful to anyone in practice.

If you've not seen [QHub](https://github.com/Quansight/qhub) you might want to check that out as a good reference.

**Comment by kpasko** [comment]
Yes totally understandable. I guess I was imagining the most vanilla thing
possible, with no actual “in practice” details like vpc/subnet settings,
scaling, load balancing, etc. just a quick terraform init, terraform apply,
and you can open a notebook and connect to a gateway, a “hello world”

The rest would be entirely up to the user to get a “real” deployment
working, and there are plenty of opinions and work to do there that
can’t/shouldn’t really be in the scope of what would be open source or in
scope of what dask-gateway community offers. Just a little something to
break down the barrier to entry and get that “ah great it works!” feeling
out of the box.

Qhub might in fact be too much as all of the (very useful and necessary)
extras and addons can be confusing/overwhelming just starting out? 🤷‍♂️
