### ISSUE TITLE
Helm chart / CI: Add install -> upgrade test

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#480]
Sometimes installing a helm chart from scratch will work after making a change, but what about if we make a change that makes existing installations of a helm chart fail to upgrade?

We should try catch those situations by having an upgrade test in our CI setup. The jupyterhub helm chart can provide an example of how this can be done, we do it for that.

**Comment by martindurant** [comment]
Can you please describe more detail of how an "upgrade" test would work? Install the most recent release and try to upgrade that? My hunch is that this would not have caught something like the CRD issue, since helm doesn't upgrade those anyway.

In general, should we always expect users to be able to use helm upgrade? Give how long ago the last release was, maybe "delete and reinstall" is a reasonable recommendation.
