### ISSUE TITLE
ModuleNotFoundError: No module named 'dask_gateway_server'

### ISSUE THREAD

**Issue by Sumit31** [dask/dask-gateway#624]
File "/home/dask/.local/bin/dask-gateway-server", line 5, in <module>
    from dask_gateway_server.app import main
ModuleNotFoundError: No module named 'dask_gateway_server'

I am getting this error on daskgateway api and controller pod can anyone advise on this ?

**Comment by consideRatio** [comment]
Please help me by describing what version is used for dask gateway, if you had a functional installation at some point in time, and what you changed when it broke, and such details - also, include configuration of possible relevance.

**Comment by Sumit31** [comment]
Hi , 
I'm installing dask gateway as a new setup via helm chart , reference : https://github.com/dask/dask-gateway/tree/main/resources/helm/dask-gateway

trying this using helm chart but the pods never came up:

pod/api-msci-dask-gateway-79dd64994b-8qkg2          0/1     CrashLoopBackOff   871 (2m14s ago)   3d1h
pod/controller-msci-dask-gateway-6948b78cd5-7l4rh   0/1     CrashLoopBackOff   871 (94s ago)     3d1h

Currently I'm are using this docker image : 2022.10.0, faced the same issue with other docker images viz  2022.6.1 and  2022.4.0.

If we check the pod logs for both api and controller i am getting this below error :

$ k logs pod/api-msci-dask-gateway-79dd64994b-8qkg2 -n <NAMESPACE>
Traceback (most recent call last):
  File "/home/dask/.local/bin/dask-gateway-server", line 5, in <module>
    from dask_gateway_server.app import main
ModuleNotFoundError: No module named 'dask_gateway_server'

Also i set the log level to INFO but couldnt find any more description via pod logs 

Please let me know if any other info is required

**Comment by consideRatio** [comment]
Please describe exactly how you installed the helm chart, the security context can be relevant.

Also please clarify if you manually customize used images, or if you switch between helm chart versions. When now debugging getting this running in the first place, don't make changes on the images - use the default images provided by the Helm chart of the specific version used. If you want an old version of the helm chart, specify that when installing the Helm chart.

**Comment by Sumit31** [comment]
As i have security restrictions from using public images i pull the image packages and retagged it with my private docker registry(azure reguistry), also in the helm chart in the tags for image which is set by "set-by-chartpress" i manually changed the tag to my custom tag name. 

Question: Does changing tags used in the image could have caused this ??

example changed from :
 
 
 image:
    name: ghcr.io/dask/dask-gateway-server
    tag: "set-by-chartpress"
    pullPolicy: IfNotPresent

 To 
 
image:
    name: < myazure acr registry>/dask-gateway-server
    tag:  2022.10.0
    pullPolicy: IfNotPresent

Also made some manuall changes in the Chart.yml file :

# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: dask-gateway
version: **2022.10.0**
appVersion: **"2022.10.0"**
description: A multi-tenant server for deploying and managing Dask clusters
home: https://gateway.dask.org/
sources:
  - https://github.com/dask/dask-gateway/
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
kubeVersion: ">=1.20.0-0"

**Comment by consideRatio** [comment]
@Sumit31 I can't say what causes this, but I can say that the CI system testing a basic installation of this Helm chart works well.

Since you described you modify a securityContext, please also provide such configuration. If you change the user used, that may very well cause this issue.

It would be good if you instaed of using the raw source code, used an actual packaged helm chart. The source code in this repo is built into the helm chart. If you use the source code directly, you have unset values like above as well as no values.schema.json file bundled with the Helm chart etc.

You can do `helm upgrade --install --repo https://helm.dask.org/ dask-gateway dask-gateway dask-gateway --version 2022.10.0 --values your-dask-gateway-config.yaml` and from that just update the image name's of relevance.

If you write incorrect configuration, you may be automatically corrected like this. Which you won't be if you just go with the not-built helm chart in the github repository.

**Comment by Sumit31** [comment]
Thanks @consideRatio . Will try using the basic installation.

**Comment by consideRatio** [comment]
Thanks for following up @Sumit31!!!
