### ISSUE TITLE
Figure out how to bootstrap the dask user for proxyuser impersonation in an EMR cluster

### ISSUE THREAD

**Issue by ericdill** [dask/dask-gateway#64]
Leaving this note here to figure out this problem later. To figure out how to run this against an actual EMR cluster with Livy enabled, the shortest path forward is to reuse the infrastructure that AWS handles for you -- it creates the Livy user, the livy keytab and adds the right proxyuser bits to the core-site.xml files so that impersonation is working properly. Ideally, we'd figure out how to do this with the `dask` user too, but that's a reasonably big lift and not really that interesting in the scope of "let's make sure this works against a real EMR cluster".

The TODO here is to figure out what the necessary bootstrap script is to add:
1. dask user to all nodes
1. dask user to the Kerberos kdc
1. dask user to the *-site.xml in the right places

For now, the docs will reflect reusing the Livy user

**Comment by AlbertDeFusco** [comment]
I've gotten it working on EMR manually following https://gateway.dask.org/install-hadoop.html with the following modifications and additions. I was able to use the `dask` username with impersonation and follow the directions to conda-pack an env and store on hdfs rather than having to install code on all of the worker nodes.

I'll practice again from scratch soon. It looks like `useradd` will need to be done in a bootstrap and the rest in an EMR Step.

##
`sudo useradd dask` on all nodes

## private and public keytab
I ran the following, uncertain if it was necessary or if I know what I'm doing.

```
kadmin -q "xst -norandkey -k /etc/dask-gateway/dask.keytab dask HTTP/{PUBLIC-FQDN}"
kadmin -q "xst -norandkey -k /etc/dask-gateway/dask.keytab dask HTTP/{PRIVATE-FQDN}"
```

## KMS
Add the poxy-user permissions to `/etc/hadoop-kms/conf/kms-site.xml` and restart `hadoop-kms`.

```xml
  <property>
    <name>hadoop.kms.proxyuser.dask.hosts</name>
    <value>*</value>
  </property>

  <property>
    <name>hadoop.kms.proxyuser.dask.groups</name>
    <value>*</value>
  </property>
```

## configure public_connect_url
In the dask-gateway config the gateway communicates with other EMR nodes over the private IP address, but with user over the public.

```python
c.DaskGateway.public_connect_url = 'http://<public-hostname-or-route53:8000'
c.DaskGateway.public_url = 'http://ip-<internal-addr>.ec2.internal:8000'
```

## restart services
I restarted these services, some of them may not have been necessary to restart

* hadoop-hdfs-namenode
* hadoop-kms
* hadoop-yarn-resourcemanager
* hadoop-yarn-timelineserver
* hadoop-yarn-proxyserver

**Comment by bschreck** [comment]
Is there a reason we need a dask user? Instead of just using the hadoop user provided by EMR initially?

**Comment by consideRatio** [comment]
I see no concrete action point for this issue, so I'll go for a close at this point.
